name: fluppy_bird
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2+1
  lottie: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Flight1.png"
flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icon/
    - assets/images/animated-photos/

    #welcome screen menu icons
    - assets/images/button-icons/play.png
    - assets/images/button-icons/skins.png
    - assets/images/button-icons/exit.png

    #plane 1 colors
    - assets/images/skins/plane_1/plane_1_blue.png
    - assets/images/skins/plane_1/plane_1_pink.png
    - assets/images/skins/plane_1/plane_1_red.png
    - assets/images/skins/plane_1/plane_1_yellow.png
    #plane 2 colors
    - assets/images/skins/plane_2/plane_2_blue.png
    - assets/images/skins/plane_2/plane_2_green.png
    - assets/images/skins/plane_2/plane_2_red.png
    - assets/images/skins/plane_2/plane_2_yellow.png
    #plane 3 colors
    - assets/images/skins/plane_3/plane_3_blue.png
    - assets/images/skins/plane_3/plane_3_green.png
    - assets/images/skins/plane_3/plane_3_red.png
    - assets/images/skins/plane_3/plane_3_yellow.png
    

  fonts:
    - family: Games
      fonts:
        - asset: assets/fonts/EquipmentPro.ttf